// src/lib/components/CallToAction.tsx
import { AppStoreLink } from '@/components/AppStoreLink'
import { CircleBackground } from '@/components/CircleBackground'
import { Container } from '@/components/Container'

export function CallToAction() {
  return (
    <section id="get-free-shares-today" className="relative overflow-hidden bg-green-900 py-20 sm:py-28">
      <div className="absolute left-20 top-1/2 -translate-y-1/2 sm:left-1/2 sm:-translate-x-1/2">
        <CircleBackground color="#fff" className="animate-spin-slower" />
      </div>
      <Container className="relative">
        <div className="mx-auto max-w-md sm:text-center">
          <h2 className="text-3xl font-medium tracking-tight text-white sm:text-4xl">Get your first tips today</h2>
          <p className="mt-4 text-lg text-green-300">
            It takes 30 seconds to sign up. Download the app and create an account today and we’ll send you a tip guaranteed to
            double your first investment.
          </p>
          <div className="mt-8 flex justify-center">
            <AppStoreLink color="white" />
          </div>
        </div>
      </Container>
    </section>
  )
}

// apps/web/src/lib/components/call-to-action.svelte
<script lang="ts">
  import * as m from '$lib/paraglide/messages'

  // import AppStoreLink from './app-store-link.svelte'
  import CircleBackground from './circle-background.svelte'
  import Container from './container.svelte'

  // import PlayStoreLink from './play-store-link.svelte'
</script>

<section class="relative overflow-hidden bg-green-900 py-20 sm:py-28">
  <!-- <div class="absolute top-1/2 left-20 -translate-y-1/2 sm:left-1/2 sm:-translate-x-1/2">
    <CircleBackground color="#fff" class="animate-spin-slower" />
  </div> -->
  <Container class="relative">
    <div class="mx-auto max-w-md sm:text-center">
      <h2 class="text-3xl font-medium tracking-tight text-white sm:text-4xl">{m.cta_title()}</h2>
      <p class="mt-4 text-lg text-green-300">{m.cta_description()}</p>
      <!-- <div class="mt-8 flex justify-center gap-x-6 gap-y-4">
        <PlayStoreLink color="white" />
        <AppStoreLink color="white" />
      </div> -->
    </div>
  </Container>
</section>
