// src/lib/components/NavLinks.tsx
'use client'

import { AnimatePresence, motion } from 'framer-motion'
import Link from 'next/link'
import { useRef, useState } from 'react'

export function NavLinks() {
  let [hoveredIndex, setHoveredIndex] = useState<number | null>(null)
  let timeoutRef = useRef<number | null>(null)

  return [
    ['Features', '/#features'],
    ['Reviews', '/#reviews'],
    ['Pricing', '/#pricing'],
    ['FAQs', '/#faqs'],
  ].map(([label, href], index) => (
    <Link
      key={label}
      href={href}
      className="relative -mx-3 -my-2 rounded-lg px-3 py-2 text-sm text-green-700 transition-colors delay-150 hover:text-green-900 hover:delay-0"
      onMouseEnter={() => {
        if (timeoutRef.current) {
          window.clearTimeout(timeoutRef.current)
        }
        setHoveredIndex(index)
      }}
      onMouseLeave={() => {
        timeoutRef.current = window.setTimeout(() => {
          setHoveredIndex(null)
        }, 200)
      }}
    >
      <AnimatePresence>
        {hoveredIndex === index && (
          <motion.span
            className="absolute inset-0 rounded-lg bg-green-100"
            layoutId="hoverBackground"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1, transition: { duration: 0.15 } }}
            exit={{
              opacity: 0,
              transition: { duration: 0.15 },
            }}
          />
        )}
      </AnimatePresence>
      <span className="relative z-10">{label}</span>
    </Link>
  ))
}

// apps/web/src/lib/components/nav-links.svelte
<script lang="ts">
  import * as m from '$lib/paraglide/messages'

  const links = [
    { label: m.nav_features(), href: '/#features' },
    { label: m.nav_pricing(), href: '/#pricing' },
    { label: m.nav_faqs(), href: '/#faqs' },
  ]
</script>

{#each links as { label, href }, index}
  <a
    {href}
    class="relative -mx-3 -my-2 rounded-lg bg-transparent px-3 py-2 text-sm text-green-700 transition-colors delay-150 hover:bg-green-100 hover:text-green-900 hover:delay-0"
  >
    <span class="relative z-10">{label}</span>
  </a>
{/each}
