// src/lib/components/Footer.tsx
import { Button } from '@/components/Button'
import { Container } from '@/components/Container'
import { TextField } from '@/components/Fields'
import { Logomark } from '@/components/Logo'
import { NavLinks } from '@/components/NavLinks'
import qrCode from '@/images/qr-code.svg'
import Image from 'next/image'
import Link from 'next/link'

function QrCodeBorder(props: React.ComponentPropsWithoutRef<'svg'>) {
  return (
    <svg viewBox="0 0 96 96" fill="none" aria-hidden="true" {...props}>
      <path
        d="M1 17V9a8 8 0 0 1 8-8h8M95 17V9a8 8 0 0 0-8-8h-8M1 79v8a8 8 0 0 0 8 8h8M95 79v8a8 8 0 0 1-8 8h-8"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </svg>
  )
}

export function Footer() {
  return (
    <footer className="border-t border-green-200">
      <Container>
        <div className="flex flex-col items-start justify-between gap-y-12 pb-6 pt-16 lg:flex-row lg:items-center lg:py-16">
          <div>
            <div className="flex items-center text-green-900">
              <Logomark className="h-10 w-10 flex-none fill-cyan-500" />
              <div className="ml-4">
                <p className="text-base font-semibold">Pocket</p>
                <p className="mt-1 text-sm">Invest at the perfect time.</p>
              </div>
            </div>
            <nav className="mt-11 flex gap-8">
              <NavLinks />
            </nav>
          </div>
          <div className="group relative -mx-4 flex items-center self-stretch p-4 transition-colors hover:bg-green-100 sm:self-auto sm:rounded-2xl lg:mx-0 lg:self-auto lg:p-6">
            <div className="relative flex h-24 w-24 flex-none items-center justify-center">
              <QrCodeBorder className="absolute inset-0 h-full w-full stroke-green-300 transition-colors group-hover:stroke-cyan-500" />
              <Image src={qrCode} alt="" unoptimized />
            </div>
            <div className="ml-8 lg:w-64">
              <p className="text-base font-semibold text-green-900">
                <Link href="#">
                  <span className="absolute inset-0 sm:rounded-2xl" />
                  Download the app
                </Link>
              </p>
              <p className="mt-1 text-sm text-green-700">Scan the QR code to download the app from the App Store.</p>
            </div>
          </div>
        </div>
        <div className="flex flex-col items-center border-t border-green-200 pb-12 pt-8 md:flex-row-reverse md:justify-between md:pt-6">
          <form className="flex w-full justify-center md:w-auto">
            <TextField
              type="email"
              aria-label="Email address"
              placeholder="Email address"
              autoComplete="email"
              required
              className="w-60 min-w-0 shrink"
            />
            <Button type="submit" color="cyan" className="ml-4 flex-none">
              <span className="hidden lg:inline">Join our newsletter</span>
              <span className="lg:hidden">Join newsletter</span>
            </Button>
          </form>
          <p className="mt-6 text-sm text-green-500 md:mt-0">&copy; Copyright {new Date().getFullYear()}. All rights reserved.</p>
        </div>
      </Container>
    </footer>
  )
}

// src/lib/components/footer.svelte
<script lang="ts">
  // import { onMount } from 'svelte'

  import qrCode from '$lib/assets/qr-code.svg'
  import * as m from '$lib/paraglide/messages'

  import Button from './button.svelte'
  import Container from './container.svelte'
  import InputField from './fields/input.svelte'
  import QrCodeBorder from './icons/qr-code-border.svelte'
  import LogoMark from './logo-mark.svelte'
  import NavLinks from './nav-links.svelte'

  // let currentYear: number

  // onMount(() => {
  //   currentYear = new Date().getFullYear()
  // })
  let isLoading = $state(false)

  const handleSubmit = async (event: Event) => {
    event.preventDefault()

    isLoading = true

    const form = event.target as HTMLFormElement
    const formData = new FormData(form)
    const email = formData.get('email') as string

    await fetch('/api/join-waitlist', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ email }),
    })

    isLoading = false
  }
</script>

<footer class="border-t border-green-200">
  <Container>
    <div class="flex flex-col items-start justify-between gap-y-12 pb-6 pt-16 lg:flex-row lg:items-center lg:py-16">
      <div>
        <div class="flex items-center text-green-900">
          <LogoMark class="h-10 w-10 flex-none fill-green-500" />
          <div class="ml-4">
            <p class="text-base font-semibold">{m.name()}</p>
            <p class="mt-1 text-sm">{m.tagline()}.</p>
          </div>
        </div>
        <nav class="mt-11 flex gap-8">
          <NavLinks />
        </nav>
      </div>
      <!-- <div
        class="group relative -mx-4 flex items-center self-stretch p-4 transition-colors hover:bg-green-100 sm:self-auto sm:rounded-2xl lg:mx-0 lg:self-auto lg:p-6"
      >
        <div class="relative flex h-24 w-24 flex-none items-center justify-center">
          <QrCodeBorder class="absolute inset-0 h-full w-full stroke-green-300 transition-colors group-hover:stroke-green-500" />
          <img
            src={qrCode}
            alt="QR Code for app download"
            loading="lazy"
            width="80"
            height="80"
            decoding="async"
            class="h-full w-full max-w-20 max-h-20"
          />
        </div>
        <div class="ml-8 lg:w-64">
          <p class="text-base font-semibold text-green-900">
            <a href="/" target="_blank">
              <span class="absolute inset-0 sm:rounded-2xl"></span>
              {m.download_app()}
            </a>
          </p>
          <p class="mt-1 text-sm text-green-700">{m.qr_code_description()}</p>
        </div>
      </div> -->
    </div>
    <div class="flex flex-col items-center border-t border-green-200 pb-12 pt-8 md:flex-row-reverse md:justify-between md:pt-6">
      <form class="flex w-full justify-center md:w-auto" onsubmit={handleSubmit}>
        <InputField
          type="email"
          name="email"
          aria-label={m.your_email()}
          placeholder={m.your_email()}
          autoComplete="email"
          required
          disabled={isLoading}
          class="w-60 min-w-0 shrink"
        />
        <Button type="submit" color="green" class="ml-4 flex-none" disabled={isLoading}>
          <span class="hidden lg:inline">{m.join_newsletter()}</span>
          <span class="lg:hidden">{m.join_newsletter()}</span>
        </Button>
      </form>
      <p class="mt-6 text-sm text-green-500 md:mt-0">
        {m.name()} — {m.tagline()}
      </p>
    </div>
  </Container>
</footer>
