// src/lib/components/Header.tsx
'use client'

import { Button } from '@/components/Button'
import { Container } from '@/components/Container'
import { Logo } from '@/components/Logo'
import { NavLinks } from '@/components/NavLinks'
import { Popover, PopoverBackdrop, PopoverButton, PopoverPanel } from '@headlessui/react'
import { AnimatePresence, motion } from 'framer-motion'
import Link from 'next/link'

function MenuIcon(props: React.ComponentPropsWithoutRef<'svg'>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden="true" {...props}>
      <path d="M5 6h14M5 18h14M5 12h14" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function ChevronUpIcon(props: React.ComponentPropsWithoutRef<'svg'>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden="true" {...props}>
      <path d="M17 14l-5-5-5 5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function MobileNavLink(props: Omit<React.ComponentPropsWithoutRef<typeof PopoverButton<typeof Link>>, 'as' | 'className'>) {
  return <PopoverButton as={Link} className="block text-base leading-7 tracking-tight text-green-700" {...props} />
}

export function Header() {
  return (
    <header>
      <nav>
        <Container className="relative z-50 flex justify-between py-8">
          <div className="relative z-10 flex items-center gap-16">
            <Link href="/" aria-label="Home">
              <Logo className="h-10 w-auto" />
            </Link>
            <div className="hidden lg:flex lg:gap-10">
              <NavLinks />
            </div>
          </div>
          <div className="flex items-center gap-6">
            <Popover className="lg:hidden">
              {({ open }) => (
                <>
                  <PopoverButton
                    className="relative z-10 -m-2 inline-flex items-center rounded-lg stroke-green-900 p-2 hover:bg-green-200/50 hover:stroke-green-600 active:stroke-green-900 ui-not-focus-visible:outline-none"
                    aria-label="Toggle site navigation"
                  >
                    {({ open }) => (open ? <ChevronUpIcon className="h-6 w-6" /> : <MenuIcon className="h-6 w-6" />)}
                  </PopoverButton>
                  <AnimatePresence initial={false}>
                    {open && (
                      <>
                        <PopoverBackdrop
                          static
                          as={motion.div}
                          initial={{ opacity: 0 }}
                          animate={{ opacity: 1 }}
                          exit={{ opacity: 0 }}
                          className="fixed inset-0 z-0 bg-green-300/60 backdrop-blur"
                        />
                        <PopoverPanel
                          static
                          as={motion.div}
                          initial={{ opacity: 0, y: -32 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{
                            opacity: 0,
                            y: -32,
                            transition: { duration: 0.2 },
                          }}
                          className="absolute inset-x-0 top-0 z-0 origin-top rounded-b-2xl bg-green-50 px-6 pb-6 pt-32 shadow-2xl shadow-green-900/20"
                        >
                          <div className="space-y-4">
                            <MobileNavLink href="/#features">Features</MobileNavLink>
                            <MobileNavLink href="/#reviews">Reviews</MobileNavLink>
                            <MobileNavLink href="/#pricing">Pricing</MobileNavLink>
                            <MobileNavLink href="/#faqs">FAQs</MobileNavLink>
                          </div>
                          <div className="mt-8 flex flex-col gap-4">
                            <Button href="/login" variant="outline">
                              Log in
                            </Button>
                            <Button href="#">Download the app</Button>
                          </div>
                        </PopoverPanel>
                      </>
                    )}
                  </AnimatePresence>
                </>
              )}
            </Popover>
            <Button href="/login" variant="outline" className="hidden lg:block">
              Log in
            </Button>
            <Button href="#" className="hidden lg:block">
              Download
            </Button>
          </div>
        </Container>
      </nav>
    </header>
  )
}

// src/lib/components/header.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'
  import { createPopover } from 'svelte-headlessui'

  import { PUBLIC_WEB_APP_DOMAIN } from '$env/static/public'
  import * as m from '$lib/paraglide/messages'

  import Button from './button.svelte'
  import Container from './container.svelte'
  import ChevronUpIcon from './icons/chevron-up.svelte'
  import MenuIcon from './icons/menu.svelte'
  import LanguageSwitcher from './language-switcher.svelte'
  import Logo from './logo.svelte'
  import NavLinks from './nav-links.svelte'

  const popover = createPopover()

  let isOpen = $state(false)

  const unsubscribe = popover.subscribe(({ expanded }) => (isOpen = expanded))

  onDestroy(() => {
    unsubscribe()
  })
</script>

<header>
  <nav>
    <Container class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 relative z-50 flex justify-between py-8">
      <div class="relative z-10 flex items-center gap-16">
        <a href="/" aria-label="Home">
          <Logo class="h-10 w-auto" />
        </a>

        <div class="hidden lg:flex lg:gap-10">
          <NavLinks />
        </div>
      </div>

      <div class="flex items-center gap-6">
        <div class="lg:hidden">
          <button
            onclick={() => (isOpen ? popover.close : popover.open)()}
            class="relative z-10 -m-2 inline-flex items-center rounded-lg stroke-green-900 p-2 hover:bg-green-200/50 hover:stroke-green-600 active:stroke-green-900"
            aria-label="Toggle site navigation"
          >
            {#if isOpen}
              <ChevronUpIcon class="h-6 w-6" />
            {:else}
              <MenuIcon class="h-6 w-6" />
            {/if}
          </button>
          {#if isOpen}
            <div use:popover.panel class="fixed inset-0 z-0 bg-green-300/60 backdrop-blur"></div>
            <div
              use:popover.panel
              class="absolute inset-x-0 top-0 z-0 origin-top rounded-b-2xl bg-green-50 px-6 pb-6 pt-32 shadow-2xl shadow-green-900/20"
            >
              <div class="space-y-4">
                <a use:popover.button class="block text-base leading-7 tracking-tight text-green-700" href="/#features"
                  >{m.nav_features()}</a
                >
                <a use:popover.button class="block text-base leading-7 tracking-tight text-green-700" href="/#pricing"
                  >{m.nav_pricing()}</a
                >
                <a use:popover.button class="block text-base leading-7 tracking-tight text-green-700" href="/#faqs"
                  >{m.nav_faqs()}</a
                >
              </div>
              <LanguageSwitcher class="mt-8" />
              <div class="mt-8 flex flex-col gap-4">
                <Button href={`https://${PUBLIC_WEB_APP_DOMAIN}/sign-in`} variant="outline">{m.sign_in()}</Button>
                <Button href={`https://${PUBLIC_WEB_APP_DOMAIN}`}>{m.try_it_out()}</Button>
              </div>
            </div>
          {/if}
        </div>

        <LanguageSwitcher class="hidden lg:flex mr-4" />

        <Button href={`https://${PUBLIC_WEB_APP_DOMAIN}/sign-in`} target="_blank" variant="outline" class="hidden! lg:block!"
          >{m.sign_in()}</Button
        >
        <Button href={`https://${PUBLIC_WEB_APP_DOMAIN}`} target="_blank" class="hidden! lg:block!">{m.try_it_out()}</Button>
      </div>
    </Container>
  </nav>
</header>
